# Generated by Django 5.1.2 on 2025-04-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ALMACEN', '0003_alter_bienesasignados_trabajo_and_more'),
        ('TRABAJOS', '0002_contenedordispositivos_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajo',
        ),
    ]
