# Generated by Django 5.1.2 on 2025-04-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRABAJOS', '0003_delete_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
