# Generated by Django 5.2 on 2025-04-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TRABAJOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('precio', models.FloatField()),
                ('numero_serie', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloEnOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('entregado', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALMACEN.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Bienes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('licitacion', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('uso', 'Bien de Uso'), ('consumo', 'Bien de Consumo')], max_length=10)),
                ('requiere_identificador', models.BooleanField(default=False)),
                ('articulo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bienes', to='ALMACEN.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categoria', to='ALMACEN.categoria'),
        ),
        migrations.CreateModel(
            name='MaterialAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRABAJOS.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('fecha_orden', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=15)),
                ('articulos', models.ManyToManyField(related_name='ordenes_de_compra', through='ALMACEN.ArticuloEnOrden', to='ALMACEN.articulo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ALMACEN.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='articuloenorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALMACEN.ordendecompra'),
        ),
        migrations.CreateModel(
            name='Sobrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('material_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sobrantes', to='ALMACEN.materialasignado')),
                ('trabajo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRABAJOS.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='SobranteAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad_usada', models.PositiveIntegerField()),
                ('sobrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ALMACEN.sobrante')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobrantes_usados', to='TRABAJOS.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='Stock', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('pendiente_a_entregar', models.PositiveIntegerField(default=0)),
                ('articulo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='ALMACEN.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_utilizados', to='TRABAJOS.trabajo')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALMACEN.stock')),
            ],
        ),
        migrations.AddField(
            model_name='materialasignado',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ALMACEN.stock'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unidad', to='ALMACEN.unidad_medida'),
        ),
        migrations.CreateModel(
            name='UnidadBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico', models.CharField(max_length=100, unique=True)),
                ('disponible', models.BooleanField(default=True)),
                ('ubicacion_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('mantenimiento', 'Mantenimiento'), ('proceso_baja', 'En proceso de baja'), ('baja_confirmada', 'Baja confirmada')], default='disponible', max_length=50)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='ALMACEN.bienes')),
            ],
        ),
        migrations.CreateModel(
            name='BienesAsignados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ALMACEN.bienes')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bienes_usados', to='TRABAJOS.trabajo')),
                ('unidades_asignadas', models.ManyToManyField(blank=True, to='ALMACEN.unidadbien')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='articuloenorden',
            unique_together={('orden', 'articulo')},
        ),
    ]
