# Generated by Django 5.2 on 2025-04-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALMACEN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazonSocial', models.CharField(max_length=100)),
                ('Direccion', models.CharField(blank=True, max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('Estado', models.BooleanField(default=True)),
                ('RUC', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Notas', models.TextField(blank=True, null=True)),
                ('Categorizacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
