# Generated by Django 5.1.2 on 2025-04-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALMACEN', '0002_provedor'),
        ('TRABAJOS', '0002_contenedordispositivos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienesasignados',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bienes_usados', to='TRABAJOS.ordenservicio'),
        ),
        migrations.AlterField(
            model_name='materialasignado',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRABAJOS.ordenservicio'),
        ),
        migrations.AlterField(
            model_name='materialutilizado',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_utilizados', to='TRABAJOS.ordenservicio'),
        ),
        migrations.AlterField(
            model_name='sobrante',
            name='trabajo_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRABAJOS.ordenservicio'),
        ),
        migrations.AlterField(
            model_name='sobranteasignado',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobrantes_usados', to='TRABAJOS.ordenservicio'),
        ),
    ]
